os: Visual Studio 2022

init:
  - ps: $Env:DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ps: $Env:DOTNET_NOLOGO=1

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: 9I/i+S+EADd9fn7bv9GtXizJbIiorRTIK+O76EE1OaLFVf+K3eWF2pKK6SaK4sY8

cache:
  - '%LocalAppData%\NuGet\Cache -> **\Homoglyph*.csproj'
  - '%LocalAppData%\NuGet\v3-cache  -> **\Homoglyph*.csproj'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%UserProfile%\.dotnet\tools -> appveyor.yml'

install:
  - ps: ./tooling.ps1

configuration:
  - Debug

version: "0.6.{build}"

dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - dotnet restore -verbosity:q

build:
  parallel: true
  verbosity: quiet

after_build:
  - ps: dotnet pack --no-restore --no-build -verbosity:q --configuration $Env:CONFIGURATION

test_script:
  - ps: ./test.ps1

artifacts:
  - path: 'src\**\Homoglyph.*.nupkg'

deploy:
  - provider: NuGet # Nuget.org
    api_key:
      secure: wB/TicV9Qsuqfs1X3excsY/wt/pBfqQDb/9kKFWQcCHTL0rQZNHaVqDiEWQ39U6L
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: /release/
  - provider: NuGet # Github packages
    server: https://nuget.pkg.github.com/ProphetLamb/index.json
    artifact: /.*\.nupkg/
    draft: true
    username: ProphetLamb
    api_key:
      secure: C8xC+nv4MSirvCA8kUoan4sz2B8aFaytWW2m4lrLqXhAnSkOmo6fN90QHiGJoSGI
    on:
      branch: /release/

for:
  - branches:
      only:
        - /release/

    configuration:
      - Release
